### ISSUE TITLE
[Request] Resizable persistant window and narrower side bar

### ISSUE THREAD

**Issue by in4matix** [luleyleo/clapgrep#4]
Thank you for this amazing App. I am starting to use it more than Snoop.
As the tile above: It would be cool if the App had a narrower side bar, and also the ability to resize the window and that the selected size is persistent across launches. Perhaps a preference option to have the ability the list the result titles only in the right pane, and then launch a separate windows, or the default app when the title is clicked?  Looking forward to future updates.

**Comment by luleyleo** [comment]
I'm glad that you like it!

Remembering the window size will definitely be implemented. I didn't think of it before because I'm using a tiling WM, but it's certainly important for floating windows.

May I ask when the sidebar is too wide for your taste? Because it seemed like a very nice width to me. But maybe the experience varies depending on the monitor you are using.

**Comment by in4matix** [comment]
> May I ask when the sidebar is too wide for your taste?

I guess it just looks abnormally wide when compared to nautilus and all other gtk4 apps.

**Comment by luleyleo** [comment]
Ah I see. But if it's the normal size, the search input would feel too small I think.
